// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

/** Slugs under `components/`, in the order they should appear in their group. */
const componentPages = (...slugs) => slugs.map((slug) => `components/${slug}`);

export default defineConfig({
  site: 'https://r0adkll.github.io',
  base: '/ditto',
  integrations: [
    starlight({
      title: 'Ditto',
      description: 'A Compose Multiplatform UI toolkit with one component API and three platform-adaptive idioms.',
      logo: { src: './src/assets/mascot.svg', alt: 'Ditto' },
      favicon: '/mascot.svg',
      customCss: ['./src/styles/brand.css'],
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/r0adkll/ditto' }],
      sidebar: [
        { label: 'Start here', items: [{ label: 'Overview', slug: '' }] },
        { label: 'Foundations', items: [{ autogenerate: { directory: 'foundations' } }] },
        // Grouped by hand rather than autogenerated: 33 components in one alphabetical list is a
        // wall, and the groups are the first thing someone browsing for "how do I ask a yes/no
        // question" needs. `check-docs.mjs` fails the build if a page is missing from this list.
        {
          label: 'Components',
          items: [
            { label: 'Actions', collapsed: true, items: componentPages('button', 'icon-button', 'toggle-button', 'floating-action-button', 'link') },
            { label: 'Selection', collapsed: true, items: componentPages('checkbox', 'radio-button', 'switch', 'chip', 'segmented-control', 'slider', 'range-slider') },
            { label: 'Text input', collapsed: true, items: componentPages('text-field', 'search-bar', 'combo-box') },
            { label: 'Containment', collapsed: true, items: componentPages('card', 'list-item', 'split-pane') },
            { label: 'Navigation', collapsed: true, items: componentPages('top-bar', 'navigation', 'tabs', 'menu', 'tree') },
            { label: 'Feedback', collapsed: true, items: componentPages('badge', 'banner', 'dialog', 'sheet', 'snackbar', 'progress-indicator', 'pull-to-refresh', 'tooltip') },
            { label: 'Desktop', collapsed: true, items: componentPages('scrollbar', 'decorated-window') },
          ],
        },
        { label: 'Reference', items: [{ label: 'API (Dokka)', link: '/api/', attrs: { target: '_blank' } }, { label: 'Full catalog', link: '/catalog/', attrs: { target: '_blank' } }] },
      ],
    }),
  ],
});
